language: c
dist: xenial
sudo: true
cache:
  directories:
  - .flatpak-builder
  timeout: 300
before_install:
  - sudo apt-add-repository -y ppa:alexlarsson/flatpak
  - sudo apt-get update -q -y
install:
  - sudo apt-get install -y flatpak-builder elfutils
  - flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak --user install flathub org.gnome.Sdk//3.28
  - flatpak --user install flathub org.gnome.Platform//3.28
  - flatpak --user install flathub org.freedesktop.Sdk.Extension.gfortran-62//1.6
script:
  - timeout 40m flatpak-builder --force-clean build/ edu.stanford.Almond.json
