language: c
sudo: true
before_install:
  - sudo apt-add-repository -y ppa:alexlarsson/flatpak
  - sudo apt-get update -q -y
install:
  - sudo apt-get install -y flatpak-builder
script:
  - flatpak-builder --force-clean build/ edu.stanford.Almond.json
